/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import javax.swing.JList;

/**
 * @author Manuel Landín Gómez
 * @author Iago Leirós Pérez
 */
public class Historico extends javax.swing.JDialog {

    /**
     * Creates new form Historico
     */
    public Historico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

   

    public JList<String> getjListHistoricoDeSesions() {
        return jListHistoricoDeSesions;
    }

    public void setjListHistoricoDeSesions(JList<String> jListHistoricoDeSesions) {
        this.jListHistoricoDeSesions = jListHistoricoDeSesions;
    }

 

    public JList<String> getjListHistoricoErros() {
        return jListHistoricoErros;
    }

    public void setjListHistoricoErros(JList<String> jListHistoricoErros) {
        this.jListHistoricoErros = jListHistoricoErros;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHistoricoEventos = new javax.swing.JPanel();
        jTabbedPaneHistoricoErros = new javax.swing.JTabbedPane();
        jPanelHistoricoErros = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHistoricoErros = new javax.swing.JList<>();
        jPanelHistoricoDeSesions = new javax.swing.JPanel();
        jScrollPaneHistoricoDeSesions = new javax.swing.JScrollPane();
        jListHistoricoDeSesions = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Históricos");
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(806, 437));

        jPanelHistoricoErros.setBackground(new java.awt.Color(255, 255, 255));

        jListHistoricoErros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListHistoricoErros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListHistoricoErrosMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jListHistoricoErros);

        javax.swing.GroupLayout jPanelHistoricoErrosLayout = new javax.swing.GroupLayout(jPanelHistoricoErros);
        jPanelHistoricoErros.setLayout(jPanelHistoricoErrosLayout);
        jPanelHistoricoErrosLayout.setHorizontalGroup(
            jPanelHistoricoErrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoErrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHistoricoErrosLayout.setVerticalGroup(
            jPanelHistoricoErrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistoricoErrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneHistoricoErros.addTab("Histórico de eventos", jPanelHistoricoErros);

        jPanelHistoricoDeSesions.setBackground(new java.awt.Color(255, 255, 255));

        jListHistoricoDeSesions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneHistoricoDeSesions.setViewportView(jListHistoricoDeSesions);

        javax.swing.GroupLayout jPanelHistoricoDeSesionsLayout = new javax.swing.GroupLayout(jPanelHistoricoDeSesions);
        jPanelHistoricoDeSesions.setLayout(jPanelHistoricoDeSesionsLayout);
        jPanelHistoricoDeSesionsLayout.setHorizontalGroup(
            jPanelHistoricoDeSesionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoDeSesionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHistoricoDeSesions, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHistoricoDeSesionsLayout.setVerticalGroup(
            jPanelHistoricoDeSesionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistoricoDeSesionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHistoricoDeSesions, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneHistoricoErros.addTab("Histórico de sesións", jPanelHistoricoDeSesions);

        javax.swing.GroupLayout jPanelHistoricoEventosLayout = new javax.swing.GroupLayout(jPanelHistoricoEventos);
        jPanelHistoricoEventos.setLayout(jPanelHistoricoEventosLayout);
        jPanelHistoricoEventosLayout.setHorizontalGroup(
            jPanelHistoricoEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneHistoricoErros)
                .addContainerGap())
        );
        jPanelHistoricoEventosLayout.setVerticalGroup(
            jPanelHistoricoEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistoricoEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneHistoricoErros)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHistoricoEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHistoricoEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListHistoricoErrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListHistoricoErrosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListHistoricoErrosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListHistoricoDeSesions;
    private javax.swing.JList<String> jListHistoricoErros;
    private javax.swing.JPanel jPanelHistoricoDeSesions;
    private javax.swing.JPanel jPanelHistoricoErros;
    private javax.swing.JPanel jPanelHistoricoEventos;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneHistoricoDeSesions;
    private javax.swing.JTabbedPane jTabbedPaneHistoricoErros;
    // End of variables declaration//GEN-END:variables
}
