package interfaceGrafica;

import datos.Conector;
import datos.Datos;
import excepcions.UsuarioNonAtopadoException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import nucleo.Horta;
import nucleo.Plantio;
import nucleo.Semente;
import usuarios.*;

/**
 * @author Manuel Landín Gómez
 * @author Iago Leirós Pérez
 */
public class Principal extends javax.swing.JFrame {

    private Sesion sesion;
    private Historico h = new Historico(this, true);

    /**
     * Crea a ventana principal do aplicativo.
     */
    public Principal() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        //ICONAS
        setIconImage(new javax.swing.ImageIcon("imaxes\\logo.png").getImage());
        jLabelIconOff.setIcon(new ImageIcon("imaxes\\logo.png"));
        jButtonAlerta.setIcon(new ImageIcon("imaxes\\aviso.png"));
        
        //DATOS
        new Datos();
        for (Semente x : Semente.getSementesDisponibles()) {
            jComboBoxSementes.addItem(x.toString());
        }
        cargarMenuConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogIniciarSesion = new javax.swing.JDialog();
        jLabelSobrenome = new javax.swing.JLabel();
        jLabelContrasinal = new javax.swing.JLabel();
        jPasswordFieldContrasinal = new javax.swing.JPasswordField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jPanelErroInicioSesion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JButton();
        jPanelDeSesion = new javax.swing.JPanel();
        jLabelTextoBenvida = new javax.swing.JLabel();
        jPanelCreacionDeHorta = new javax.swing.JPanel();
        jScrollPaneDaMinaHorta = new javax.swing.JScrollPane();
        jListPlantios = new javax.swing.JList<>();
        jLabelAMinaHorta = new javax.swing.JLabel();
        jPanelDatosDoPlantio = new javax.swing.JPanel();
        jLabelDatosPlantio = new javax.swing.JLabel();
        jLabelDatosDoPlantioNome = new javax.swing.JLabel();
        jLabelDatosDoPlantioSemente = new javax.swing.JLabel();
        jLabelDatosDoPlantioSectores = new javax.swing.JLabel();
        jProgressBarEvolucionPlantio = new javax.swing.JProgressBar();
        jLabelEvolucionColleita = new javax.swing.JLabel();
        jLabelDatosPlantioAuga = new javax.swing.JLabel();
        jLabelDatosPlantioNutrientes = new javax.swing.JLabel();
        jLabelDatosPlantioLuz = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonEliminarPlantio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCantidadeSementes = new javax.swing.JLabel();
        jComboBoxCantidadeSementes = new javax.swing.JComboBox<>();
        jLabelCrearPlantio = new javax.swing.JLabel();
        jLabelNomePlantio = new javax.swing.JLabel();
        jComboBoxSementes = new javax.swing.JComboBox<>();
        jTextFieldNomePlantio = new javax.swing.JTextField();
        jLabelSementeSelecionada = new javax.swing.JLabel();
        jButtonCrearHorta = new javax.swing.JButton();
        jPanelAvisos = new javax.swing.JPanel();
        jButtonAlerta = new javax.swing.JButton();
        jPanelDeSesionOff = new javax.swing.JPanel();
        jLabelIconOff = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSesion = new javax.swing.JMenu();
        jMenuItemIniciarSesion = new javax.swing.JMenuItem();
        jMenuItemExportarHorta = new javax.swing.JMenuItem();
        jMenuItemCrearNovoUsuario = new javax.swing.JMenuItem();
        jMenuItemPecharSesion = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        jDialogIniciarSesion.setTitle("Iniciar sesión");
        jDialogIniciarSesion.setModal(true);
        jDialogIniciarSesion.setPreferredSize(new java.awt.Dimension(398, 250));
        jDialogIniciarSesion.setResizable(false);
        jDialogIniciarSesion.setSize(new java.awt.Dimension(398, 250));

        jLabelSobrenome.setText("Usuario:");

        jLabelContrasinal.setText("Contrasinal: ");

        jPasswordFieldContrasinal.setMinimumSize(new java.awt.Dimension(10, 20));
        jPasswordFieldContrasinal.setPreferredSize(new java.awt.Dimension(10, 20));
        jPasswordFieldContrasinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContrasinalActionPerformed(evt);
            }
        });

        jTextFieldSobrenome.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextFieldSobrenome.setPreferredSize(new java.awt.Dimension(10, 20));
        jTextFieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobrenomeActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Erro ao iniciar a sesión. Ténteo de novo.");

        javax.swing.GroupLayout jPanelErroInicioSesionLayout = new javax.swing.GroupLayout(jPanelErroInicioSesion);
        jPanelErroInicioSesion.setLayout(jPanelErroInicioSesionLayout);
        jPanelErroInicioSesionLayout.setHorizontalGroup(
            jPanelErroInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelErroInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelErroInicioSesionLayout.setVerticalGroup(
            jPanelErroInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelErroInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonIniciarSesion.setText("Iniciar sesión");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogIniciarSesionLayout = new javax.swing.GroupLayout(jDialogIniciarSesion.getContentPane());
        jDialogIniciarSesion.getContentPane().setLayout(jDialogIniciarSesionLayout);
        jDialogIniciarSesionLayout.setHorizontalGroup(
            jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                .addGroup(jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabelSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                        .addGroup(jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelErroInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelContrasinal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldContrasinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialogIniciarSesionLayout.setVerticalGroup(
            jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogIniciarSesionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasinal)
                    .addComponent(jPasswordFieldContrasinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelErroInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jDialogIniciarSesion.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hortas");
        setResizable(false);

        jLabelTextoBenvida.setForeground(new java.awt.Color(51, 204, 0));
        jLabelTextoBenvida.setText("Benvido");

        jListPlantios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPlantiosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListPlantiosMousePressed(evt);
            }
        });
        jScrollPaneDaMinaHorta.setViewportView(jListPlantios);

        jLabelAMinaHorta.setText("A miña horta");

        jPanelDatosDoPlantio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDatosPlantio.setText("Datos do plantío:");

        jLabelDatosDoPlantioNome.setText("Nome:");

        jLabelDatosDoPlantioSemente.setText("Semente:");

        jLabelDatosDoPlantioSectores.setText("Sectores:");

        jProgressBarEvolucionPlantio.setForeground(new java.awt.Color(0, 204, 0));

        jLabelEvolucionColleita.setText("Evolución ata a colleita:");

        jLabelDatosPlantioAuga.setText("Auga (ml/día):");

        jLabelDatosPlantioNutrientes.setText("Nutrintes (g/día): ");

        jLabelDatosPlantioLuz.setText("Luz solar (h/día):");

        jButtonEliminarPlantio.setText("Eliminar");
        jButtonEliminarPlantio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPlantioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosDoPlantioLayout = new javax.swing.GroupLayout(jPanelDatosDoPlantio);
        jPanelDatosDoPlantio.setLayout(jPanelDatosDoPlantioLayout);
        jPanelDatosDoPlantioLayout.setHorizontalGroup(
            jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDoPlantioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosDoPlantioLayout.createSequentialGroup()
                        .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatosPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosDoPlantioLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelDatosDoPlantioSectores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatosDoPlantioSemente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatosDoPlantioNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatosPlantioNutrientes, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabelDatosPlantioAuga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatosPlantioLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelDatosDoPlantioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosDoPlantioLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jProgressBarEvolucionPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelEvolucionColleita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosDoPlantioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDatosDoPlantioLayout.setVerticalGroup(
            jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDoPlantioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelDatosPlantio)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosDoPlantioNome)
                    .addComponent(jLabelDatosPlantioAuga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosDoPlantioSemente)
                    .addComponent(jLabelDatosPlantioNutrientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosDoPlantioSectores)
                    .addComponent(jLabelDatosPlantioLuz))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosDoPlantioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarEvolucionPlantio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEvolucionColleita, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonEliminarPlantio)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCantidadeSementes.setText("Cantidade:");

        jComboBoxCantidadeSementes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabelCrearPlantio.setText("Crea o teu primeiro plantío:");

        jLabelNomePlantio.setText("Nome:");

        jTextFieldNomePlantio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePlantioActionPerformed(evt);
            }
        });

        jLabelSementeSelecionada.setText("Semente:");

        jButtonCrearHorta.setText("Crear");
        jButtonCrearHorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearHortaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelNomePlantio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomePlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelSementeSelecionada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSementes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabelCantidadeSementes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCantidadeSementes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButtonCrearHorta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelCrearPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelCrearPlantio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePlantio)
                    .addComponent(jTextFieldNomePlantio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSementes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSementeSelecionada)
                    .addComponent(jButtonCrearHorta)
                    .addComponent(jLabelCantidadeSementes)
                    .addComponent(jComboBoxCantidadeSementes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCreacionDeHortaLayout = new javax.swing.GroupLayout(jPanelCreacionDeHorta);
        jPanelCreacionDeHorta.setLayout(jPanelCreacionDeHortaLayout);
        jPanelCreacionDeHortaLayout.setHorizontalGroup(
            jPanelCreacionDeHortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreacionDeHortaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreacionDeHortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCreacionDeHortaLayout.createSequentialGroup()
                        .addComponent(jScrollPaneDaMinaHorta, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosDoPlantio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCreacionDeHortaLayout.createSequentialGroup()
                        .addComponent(jLabelAMinaHorta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCreacionDeHortaLayout.setVerticalGroup(
            jPanelCreacionDeHortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreacionDeHortaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabelAMinaHorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreacionDeHortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosDoPlantio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDaMinaHorta, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        jButtonAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAvisosLayout = new javax.swing.GroupLayout(jPanelAvisos);
        jPanelAvisos.setLayout(jPanelAvisosLayout);
        jPanelAvisosLayout.setHorizontalGroup(
            jPanelAvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvisosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAvisosLayout.setVerticalGroup(
            jPanelAvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDeSesionLayout = new javax.swing.GroupLayout(jPanelDeSesion);
        jPanelDeSesion.setLayout(jPanelDeSesionLayout);
        jPanelDeSesionLayout.setHorizontalGroup(
            jPanelDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCreacionDeHorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDeSesionLayout.createSequentialGroup()
                        .addComponent(jLabelTextoBenvida, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDeSesionLayout.setVerticalGroup(
            jPanelDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeSesionLayout.createSequentialGroup()
                .addGroup(jPanelDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDeSesionLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelTextoBenvida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCreacionDeHorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDeSesionOffLayout = new javax.swing.GroupLayout(jPanelDeSesionOff);
        jPanelDeSesionOff.setLayout(jPanelDeSesionOffLayout);
        jPanelDeSesionOffLayout.setHorizontalGroup(
            jPanelDeSesionOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeSesionOffLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabelIconOff, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanelDeSesionOffLayout.setVerticalGroup(
            jPanelDeSesionOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeSesionOffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIconOff, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuSesion.setText("Sesión");
        jMenuSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSesionActionPerformed(evt);
            }
        });

        jMenuItemIniciarSesion.setText("Iniciar sesión");
        jMenuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIniciarSesionActionPerformed(evt);
            }
        });
        jMenuSesion.add(jMenuItemIniciarSesion);

        jMenuItemExportarHorta.setText("Exportar horta");
        jMenuItemExportarHorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportarHortaActionPerformed(evt);
            }
        });
        jMenuSesion.add(jMenuItemExportarHorta);

        jMenuItemCrearNovoUsuario.setText("Rexistrarse");
        jMenuItemCrearNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearNovoUsuarioActionPerformed(evt);
            }
        });
        jMenuSesion.add(jMenuItemCrearNovoUsuario);

        jMenuItemPecharSesion.setText("Pechar sesión");
        jMenuItemPecharSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPecharSesionActionPerformed(evt);
            }
        });
        jMenuSesion.add(jMenuItemPecharSesion);

        jMenuItemSair.setText("Saír");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSesion.add(jMenuItemSair);

        jMenuBar1.add(jMenuSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDeSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanelDeSesionOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDeSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanelDeSesionOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Rexistra os inicios de sesión nun histórico da BD.
     *
     * @see datos.Conector
     */
    private void rexistrarIniciosSesion() {
        h.getjListHistoricoDeSesions().setListData(Datos.queryRegistrosSesion(sesion));
    }

    private void cargarMenuConfig() {

        if (sesion == null) {
            jPanelDeSesionOff.setVisible(true);
            jPanelDeSesion.setVisible(false);
            jMenuItemIniciarSesion.setVisible(true);
            jMenuItemPecharSesion.setVisible(false);
            jMenuItemCrearNovoUsuario.setVisible(true);
            jMenuItemExportarHorta.setVisible(false);
        } else {
            jMenuItemExportarHorta.setVisible(true);
            jPanelDeSesionOff.setVisible(false);
            jPanelDeSesion.setVisible(true);
            jMenuItemIniciarSesion.setVisible(false);
            jMenuItemPecharSesion.setVisible(true);
            jMenuItemCrearNovoUsuario.setVisible(false);

        }
    }

    /**
     * Carga os plantíos contra a base de datos.
     *
     * @see datos.Conector
     */
    private void cargarPlantios() {
        Conector c = new Conector();
        c.setQuery("select p.nome, s.nome, p.num_sementes from plantios as p "
                + "inner join sementes as s on p.semente = s.id_semente  where "
                + "usuario = (select id_usuario from usuarios where sobrenome = '"
                + sesion.getSesionDe().getSobrenome() + "')");
        try {

            sesion.getSesionDe().setHorta(new Horta(sesion.getSesionDe()));

            while (c.getResultSet().next()) {
                sesion.getSesionDe().getHorta().engadirPlantio(
                        c.getResultSet().getString(1),
                        Semente.getSementePorNome(c.getResultSet().getString(2)),
                        c.getResultSet().getInt(3)
                );
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        c.close();
    }

    /**
     * Actualiza os históricos contra a base de datos.
     *
     * @see datos.Conector
     */
    private void actualizarHistoricos() {

        ArrayList<String> dataErro = new ArrayList<>();
        ArrayList<String> descricion = new ArrayList<>();
        Conector c = new Conector();
        c.setQuery("select * from historico_insercion_plantios where usuario = "
                + "(select id_usuario from usuarios where sobrenome = '"
                + sesion.getSesionDe().getSobrenome() + "') order by data_mensaxe desc");
        try {
            while (c.getResultSet().next()) {
                dataErro.add(c.getResultSet().getDate(2).toString());
                descricion.add(c.getResultSet().getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        String[] de = new String[dataErro.size()];
        int i = 0;
        for (String str : dataErro) {
            de[i] = str + ": " + descricion.get(i);
            i++;
        }
        h.getjListHistoricoErros().setListData(de);

        c.close();
    }

    private void actualizarDatos() {
        jListPlantios.setListData(sesion.getSesionDe().getHorta().getListaPlantios());
        jLabelNomePlantio.setForeground(Color.black);

    }

    /**
     * Borra os campos de texto e seleccións da interface.
     */
    private void limparInterface() {
        String[] s = {};
        String str = "";
        jListPlantios.setListData(s);
        jPasswordFieldContrasinal.setText(str);
        jTextFieldSobrenome.setText(str);
        jTextFieldNomePlantio.setText(str);
        jTextFieldNomePlantio.setText(str);
        jComboBoxSementes.setSelectedIndex(0);
        jComboBoxCantidadeSementes.setSelectedIndex(0);
        jProgressBarEvolucionPlantio.setValue(0);
        jPanelDatosDoPlantio.setVisible(false);
        jLabelNomePlantio.setForeground(Color.black);
    }


    private void jMenuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIniciarSesionActionPerformed
        limparInterface();
        jPanelErroInicioSesion.setVisible(false);
        jDialogIniciarSesion.setLocationRelativeTo(null);
        jDialogIniciarSesion.setVisible(true);
        
        cargarMenuConfig();


    }//GEN-LAST:event_jMenuItemIniciarSesionActionPerformed

    private void jMenuItemPecharSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPecharSesionActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Confirma que desexa cerrar a sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (op == 0) {
            sesion = null;
            jMenuItemIniciarSesion.setVisible(true);
            jMenuItemPecharSesion.setVisible(false);
            jPanelDeSesion.setVisible(false);
            jMenuItemCrearNovoUsuario.setVisible(true);
            limparInterface();
            cargarMenuConfig();
        }
        
    }//GEN-LAST:event_jMenuItemPecharSesionActionPerformed

    private void jMenuSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSesionActionPerformed
        
    }//GEN-LAST:event_jMenuSesionActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        int op = 0;
        if (sesion != null) {
            op = JOptionPane.showConfirmDialog(this, "Confirma que desexa saír?", "Saír", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        }
        if (op == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jTextFieldNomePlantioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePlantioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePlantioActionPerformed

    private void jButtonCrearHortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearHortaActionPerformed
        try {
            if (sesion.getSesionDe().getHorta() == null) {
                sesion.getSesionDe().setHorta(new Horta(sesion.getSesionDe()));
            }
            if (jTextFieldNomePlantio.getText().isEmpty() || jTextFieldNomePlantio.getText().isBlank()) {
                jLabelNomePlantio.setForeground(Color.red);
                jTextFieldNomePlantio.requestFocus();
            } else {
                jLabelNomePlantio.setForeground(Color.black);
                if (sesion.getSesionDe().getHorta().getPlantios().contains(new Plantio(jTextFieldNomePlantio.getText(),
                        Semente.getSementePorNome((jComboBoxSementes.getSelectedItem()).toString()),
                        Integer.parseInt((String) jComboBoxCantidadeSementes.getSelectedItem()), sesion.getSesionDe()))) {
                    JOptionPane.showMessageDialog(this, "Xa existe un plantío con ese nome.", "ERRO", JOptionPane.ERROR_MESSAGE);
                } else {
                    Conector c = null;
                    sesion.getSesionDe().getHorta().engadirPlantio(jTextFieldNomePlantio.getText(), Semente.getSementePorNome((jComboBoxSementes.getSelectedItem()).toString()), Integer.parseInt((String) jComboBoxCantidadeSementes.getSelectedItem()));
                    c = new Conector();
                    c.setUpdate("call insertar_plantio('"
                            + sesion.getSesionDe().getSobrenome() + "','"
                            + jTextFieldNomePlantio.getText() + "','"
                            + jComboBoxSementes.getSelectedItem().toString() + "',"
                            + Integer.parseInt((String) jComboBoxCantidadeSementes.getSelectedItem())
                            + ",@x)");
                    jLabelCrearPlantio.setText("Engadir un novo plantío:");
                    jButtonCrearHorta.setText("Engadir");
                    jListPlantios.setListData(sesion.getSesionDe().getHorta().getListaPlantios());
                    c.close();
                }
                jTextFieldNomePlantio.setText("");
                jComboBoxSementes.setSelectedIndex(0);
                jComboBoxCantidadeSementes.setSelectedIndex(0);

                actualizarDatos();
            }
        } catch (Exception e) {
            System.out.println("erro");
        }

    }//GEN-LAST:event_jButtonCrearHortaActionPerformed

    private void jListPlantiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPlantiosMouseClicked

    }//GEN-LAST:event_jListPlantiosMouseClicked

    private void jListPlantiosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPlantiosMousePressed
        if (jListPlantios.getSelectedValue() != null) {
            jLabelDatosDoPlantioNome.setText("Nome: " + jListPlantios.getSelectedValue());
            jLabelDatosDoPlantioSectores.setText("Sectores: " + sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).getNumSectores());
            jLabelDatosDoPlantioSemente.setText("Semente: " + sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).getSemente().getNome());
            jLabelDatosPlantioAuga.setText("Auga (ml/día): " + sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).getSemente().getCantidadeAuga());
            jLabelDatosPlantioNutrientes.setText("Nutrientes (g/día): " + sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).getSemente().getCantidadeNutrientes());
            jLabelDatosPlantioLuz.setText("Luz (h/día): " + sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).getSemente().getCantidadeLuz());
            jProgressBarEvolucionPlantio.setValue(sesion.getSesionDe().getHorta().buscarPlantioPorNome(sesion.getSesionDe().getSobrenome(), jListPlantios.getSelectedValue()).porcentaxeCrecemeto());
            jPanelDatosDoPlantio.setVisible(true);
        } else {
            jPanelDatosDoPlantio.setVisible(false);
        }
    }//GEN-LAST:event_jListPlantiosMousePressed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed

        try {
            String sobrenome = jTextFieldSobrenome.getText();
            String password = jPasswordFieldContrasinal.getText();
            sesion = new Sesion(sobrenome, password);
            jMenuItemIniciarSesion.setVisible(false);
            jMenuItemPecharSesion.setVisible(true);
            jMenuItemCrearNovoUsuario.setVisible(false);
            jDialogIniciarSesion.setVisible(false);
            jLabelTextoBenvida.setText("Benvido " + sobrenome + ".");
            jPanelDeSesion.setVisible(true);
            rexistrarIniciosSesion();
            actualizarHistoricos();
            cargarPlantios();

            if (sesion.getSesionDe() instanceof UsrCliente && sesion.getSesionDe().getHorta() == null) {
                jLabelCrearPlantio.setText("Crea o teu primeiro plantío:");
                jPanelCreacionDeHorta.setVisible(true);
            } else if (sesion.getSesionDe() instanceof UsrCliente && sesion.getSesionDe().getHorta() != null) {
                actualizarDatos();
                jLabelCrearPlantio.setText("Engade un novo plantío:");
                jPanelCreacionDeHorta.setVisible(true);
            } else {
                jPanelCreacionDeHorta.setVisible(false);
            }

        } catch (UsuarioNonAtopadoException e) {
            jPanelErroInicioSesion.setVisible(true);
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jPasswordFieldContrasinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasinalActionPerformed

    private void jTextFieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSobrenomeActionPerformed

    private void jMenuItemCrearNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearNovoUsuarioActionPerformed
        PaxinaRexistro pr = new PaxinaRexistro();
        pr.setVisible(true);

    }//GEN-LAST:event_jMenuItemCrearNovoUsuarioActionPerformed

    private void jButtonEliminarPlantioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPlantioActionPerformed
        int op = JOptionPane.showConfirmDialog(this,
                "Está seguro que desexa borrar este plantío?",
                "Confirmar borrado",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (op == 0) {
            sesion.getSesionDe().getHorta().borrarPlantio(jListPlantios.getSelectedValue());
            String[] str = {};
            jListPlantios.setListData(sesion.getSesionDe().getHorta().getListaPlantios());
            jPanelDatosDoPlantio.setVisible(false);
        }

    }//GEN-LAST:event_jButtonEliminarPlantioActionPerformed

    private void jButtonAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlertaActionPerformed
        jButtonAlerta.setIcon(new javax.swing.ImageIcon("imaxes\\aviso.png"));
        actualizarHistoricos();
        h.setVisible(true);
    }//GEN-LAST:event_jButtonAlertaActionPerformed

    private void jMenuItemExportarHortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportarHortaActionPerformed
        if (!Datos.exportarDatos(sesion)) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar a exportanción de datos.");
        } else {
            JOptionPane.showMessageDialog(this, "Exportación realizada con éxito.");
        }
    }//GEN-LAST:event_jMenuItemExportarHortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlerta;
    private javax.swing.JButton jButtonCrearHorta;
    private javax.swing.JButton jButtonEliminarPlantio;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JComboBox<String> jComboBoxCantidadeSementes;
    private javax.swing.JComboBox<String> jComboBoxSementes;
    private javax.swing.JDialog jDialogIniciarSesion;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAMinaHorta;
    private javax.swing.JLabel jLabelCantidadeSementes;
    private javax.swing.JLabel jLabelContrasinal;
    private javax.swing.JLabel jLabelCrearPlantio;
    private javax.swing.JLabel jLabelDatosDoPlantioNome;
    private javax.swing.JLabel jLabelDatosDoPlantioSectores;
    private javax.swing.JLabel jLabelDatosDoPlantioSemente;
    private javax.swing.JLabel jLabelDatosPlantio;
    private javax.swing.JLabel jLabelDatosPlantioAuga;
    private javax.swing.JLabel jLabelDatosPlantioLuz;
    private javax.swing.JLabel jLabelDatosPlantioNutrientes;
    private javax.swing.JLabel jLabelEvolucionColleita;
    private javax.swing.JLabel jLabelIconOff;
    private javax.swing.JLabel jLabelNomePlantio;
    private javax.swing.JLabel jLabelSementeSelecionada;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelTextoBenvida;
    private javax.swing.JList<String> jListPlantios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCrearNovoUsuario;
    private javax.swing.JMenuItem jMenuItemExportarHorta;
    private javax.swing.JMenuItem jMenuItemIniciarSesion;
    private javax.swing.JMenuItem jMenuItemPecharSesion;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAvisos;
    private javax.swing.JPanel jPanelCreacionDeHorta;
    private javax.swing.JPanel jPanelDatosDoPlantio;
    private javax.swing.JPanel jPanelDeSesion;
    private javax.swing.JPanel jPanelDeSesionOff;
    private javax.swing.JPanel jPanelErroInicioSesion;
    private javax.swing.JPasswordField jPasswordFieldContrasinal;
    private javax.swing.JProgressBar jProgressBarEvolucionPlantio;
    private javax.swing.JScrollPane jScrollPaneDaMinaHorta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldNomePlantio;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
